language: java
jdk:
  - openjdk8
install:
  - mkdir -p src/main/resources
  - curl -L -o src/main/resources/qqwry.dat https://github.com/out0fmemory/qqwry.dat/raw/master/qqwry_lastest.dat 
script: 
  - ./gradlew check
cache:
  directories:
  - $HOME/.gradle
