language: java
jdk:
  - openjdk8
install:
  - mkdir -p src/main/resources
  - curl -L -o src/main/resources/qqwry.dat https://github.com/metowolf/qqwry.dat/releases/latest/download/qqwry.dat
script: 
  - ./gradlew check
cache:
  directories:
  - $HOME/.gradle
